# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{typedown}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["wrimle"]
  s.date = %q{2010-08-13}
  s.default_executable = %q{typedown}
  s.description = %q{Typedown is a markdown preprocessor which forwards it's output to a markdown parser. Presently bluecloth}
  s.email = %q{rmyrland@gmail.com}
  s.executables = ["typedown"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "History.txt",
     "Manifest.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/typedown",
     "lib/typedown.rb",
     "lib/typedown/document.rb",
     "script/console",
     "script/destroy",
     "script/generate",
     "test/data/example.tpd",
     "test/test_helper.rb",
     "test/test_typedown.rb"
  ]
  s.homepage = %q{http://github.com/wrimle/typedown}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A markdown dialect optimized for fast typing on mobile devices}
  s.test_files = [
    "test/test_helper.rb",
     "test/test_typedown.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bluecloth>, [">= 2.0.7"])
    else
      s.add_dependency(%q<bluecloth>, [">= 2.0.7"])
    end
  else
    s.add_dependency(%q<bluecloth>, [">= 2.0.7"])
  end
end

